### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Helias** [xan1242/CrashBashEx#1]
Hello, I added a reference for this project in this repository https://github.com/Helias/Crash-Bandicoot-Resources where I would like to keep all the references about crash bandicoot reverse engineering tools or any remaster/rework of it.

**Comment by xan1242** [comment]
Okay, I'm fine with that! Thank you for telling me about this!

This is currently _only_ for extracting the data and nothing more.

It could be made to repack as well for native game modding, which I might do in the future.
